version: '3'

volumes:
    serialminder-db:
services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    env_file:
      - .env_app
    restart: always
    build:
      context: .
    container_name: app
    depends_on:
      - serialminder-db
    ports:
      - "10041:10042"

  serialminder-db:
    image: 'postgres:13.1-alpine'
    env_file:
      - .env_db
    restart: always
    container_name: serialminder-db
    volumes:
      - serialminder-db:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"